(source gnu)
(source melpa)

(depends-on "cask")

;;Themes
(depends-on "atom-one-dark-theme")

;;Packages
(depends-on "web-mode")
(depends-on "prettier-js")
(depends-on "emmet-mode")
(depends-on "js2-mode")
(depends-on "move-text")
