(source gnu)
(source melpa)
(source melpa)

(depends-on "cask")

;;Theme
;;(depends-on "spacegray-theme")
;;(depends-on "niflheim-theme")
(depends-on "color-theme-solarized")
;;(depends-on "darcula-theme")

;;Packages
(depends-on "ace-jump-mode")
(depends-on "auto-complete")
(depends-on "drupal-mode")
(depends-on "dash")
(depends-on "emmet-mode")
(depends-on "expand-region")
(depends-on "helm-projectile")
(depends-on "flx-ido")
(depends-on "js2-mode")
(depends-on "magit")
(depends-on "move-text")
(depends-on "neotree")
(depends-on "php-mode")
(depends-on "projectile")
(depends-on "scss-mode")
(depends-on "smooth-scrolling")
(depends-on "org-trello")
(depends-on "yasnippet")
(depends-on "visual-fill-column")
(depends-on "web-mode")
(depends-on "multiple-cursors")
